// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/empty.proto

package bolg_developers.sumimasen.api;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.Empty)
    com.google.protobuf.MessageLiteOrBuilder {
}
