// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/sumimasen.proto

package bolg_developers.sumimasen.api;

public interface SumimasenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.SumimasenResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
