// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/sumimasen.proto

package bolg_developers.sumimasen.api;

public interface SumimasenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.SumimasenRequest)
    com.google.protobuf.MessageLiteOrBuilder {
}
